# <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://rediscloud:Im8keAFNOrxQu5XCseXgLwZcY48TxaXL@redis-10850.c11.us-east-1-2.ec2.cloud.redislabs.com:10850
  channel_prefix: playmatch_production

   
