---
development:
  cloud_name: yasirmalik
  api_key: '438329731972895'
  api_secret: Ju2ru2RJj4KLnuBGqm-qqK4P4yY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: yasirmalik
  api_key: '438329731972895'
  api_secret: Ju2ru2RJj4KLnuBGqm-qqK4P4yY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: yasirmalik
  api_key: '438329731972895'
  api_secret: Ju2ru2RJj4KLnuBGqm-qqK4P4yY
  enhance_image_tag: true
  static_file_support: false
